export const LOGIN_HEADER_BUTTON = '[data-analytics-id="header.login"]'
export const LOGIN_EMAIL = 'div.form-group-inner input'
export const LOGIN_TRY_BUTTON = '[data-analytics-id="button.try"]'
export const SEARCH_INPUT = '[name="search"]'
export const CONTACTS_TABLE_ADD_BUTTON = '[data-analytics-id="contactsTable.buttons.addContact"]'
export const CONTACTS_SAVE_BUTTON = '[data-analytics-id="contacts.buttons.save"]'
export const CONTACTS_NAME_INPUT = '[id="invoice_attributes_name"], [name="invoice_attributes_name"]'
export const CONTACTS_COMPANY_NUMBER_INPUT = '[id="invoice_attributes_company_number"], [name="invoice_attributes_company_number"]'
export const NAVBAR_NAVIGATION = 'ul.navbar-navigation > li'
export const CONTACTS_EMAIL = '[id="invoice_attributes_email"]'
export const ICON_EDIT = '[data-analytics-id="icon-edit"]'
export const CARET_WRAPPER = '[class="caret-wrapper"]'
export const CREATE_INVOICE_BUTTON = '[data-analytics-id="button.createInvoice"]'
export const REGISTRATION_NUMBER_INPUT = '[name="number"]'
export const REFERENCE_INPUT = '[name="reference"], [name="registration_number"]'
export const INVOICE_SELLER_NAME_INPUT = '[id="invoice_seller_attributes_name"], [id="invoice_seller_attributes_company_number"]'
export const SAVE_BUTTON = '[data-analytics-id="form.invoiceForm.buttons.save"]';
export const ALERT_TITLE = '.el-alert__title';
export const CONTACTS_BREADCRUMBS = '[data-analytics-id="breadcrumbs.contacts"]';
export const LABEL_FOR_PRICE_INPUT = 'label[for="lines-0-price"]'
export const FIRST_ROW_FIRST_COLUMN = 'tbody tr:eq(0) td:eq(0)'
export const FIRST_ROW_SECOND_COLUMN = 'tbody tr:eq(0) td:eq(1)'
export const FIRST_ROW_THIRD_COLUMN = 'tbody tr:eq(0) td:eq(2)'
export const FIRST_ROW_FIFTH_COLUMN = 'tbody tr:eq(0) td:eq(4)'
export const FIRST_ROW_SIXTH_COLUMN = 'tbody tr:eq(0) td:eq(5)'